// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs/v1/logs.proto

package io.opentelemetry.proto.logs.v1;

public final class LogsProto {
  private LogsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022logs/v1/logs.proto\022\033opentelemetry.prot" +
      "o.logs.v1\032\026common/v1/common.proto\032\032resou" +
      "rce/v1/resource.proto\"L\n\010LogsData\022@\n\rres" +
      "ource_logs\030\001 \003(\0132).opentelemetry.proto.l" +
      "ogs.v1.ResourceLogs\"\276\001\n\014ResourceLogs\022;\n\010" +
      "resource\030\001 \001(\0132).opentelemetry.proto.res" +
      "ource.v1.Resource\022]\n\034instrumentation_lib" +
      "rary_logs\030\002 \003(\01327.opentelemetry.proto.lo" +
      "gs.v1.InstrumentationLibraryLogs\022\022\n\nsche" +
      "ma_url\030\003 \001(\t\"\305\001\n\032InstrumentationLibraryL" +
      "ogs\022V\n\027instrumentation_library\030\001 \001(\01325.o" +
      "pentelemetry.proto.common.v1.Instrumenta" +
      "tionLibrary\022;\n\013log_records\030\002 \003(\0132&.opent" +
      "elemetry.proto.logs.v1.LogRecord\022\022\n\nsche" +
      "ma_url\030\003 \001(\t\"\367\002\n\tLogRecord\022\026\n\016time_unix_" +
      "nano\030\001 \001(\006\022\037\n\027observed_time_unix_nano\030\013 " +
      "\001(\006\022D\n\017severity_number\030\002 \001(\0162+.opentelem" +
      "etry.proto.logs.v1.SeverityNumber\022\025\n\rsev" +
      "erity_text\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\0225\n\004body\030\005" +
      " \001(\0132\'.opentelemetry.proto.common.v1.Any" +
      "Value\022;\n\nattributes\030\006 \003(\0132\'.opentelemetr" +
      "y.proto.common.v1.KeyValue\022 \n\030dropped_at" +
      "tributes_count\030\007 \001(\r\022\r\n\005flags\030\010 \001(\007\022\020\n\010t" +
      "race_id\030\t \001(\014\022\017\n\007span_id\030\n \001(\014*\303\005\n\016Sever" +
      "ityNumber\022\037\n\033SEVERITY_NUMBER_UNSPECIFIED" +
      "\020\000\022\031\n\025SEVERITY_NUMBER_TRACE\020\001\022\032\n\026SEVERIT" +
      "Y_NUMBER_TRACE2\020\002\022\032\n\026SEVERITY_NUMBER_TRA" +
      "CE3\020\003\022\032\n\026SEVERITY_NUMBER_TRACE4\020\004\022\031\n\025SEV" +
      "ERITY_NUMBER_DEBUG\020\005\022\032\n\026SEVERITY_NUMBER_" +
      "DEBUG2\020\006\022\032\n\026SEVERITY_NUMBER_DEBUG3\020\007\022\032\n\026" +
      "SEVERITY_NUMBER_DEBUG4\020\010\022\030\n\024SEVERITY_NUM" +
      "BER_INFO\020\t\022\031\n\025SEVERITY_NUMBER_INFO2\020\n\022\031\n" +
      "\025SEVERITY_NUMBER_INFO3\020\013\022\031\n\025SEVERITY_NUM" +
      "BER_INFO4\020\014\022\030\n\024SEVERITY_NUMBER_WARN\020\r\022\031\n" +
      "\025SEVERITY_NUMBER_WARN2\020\016\022\031\n\025SEVERITY_NUM" +
      "BER_WARN3\020\017\022\031\n\025SEVERITY_NUMBER_WARN4\020\020\022\031" +
      "\n\025SEVERITY_NUMBER_ERROR\020\021\022\032\n\026SEVERITY_NU" +
      "MBER_ERROR2\020\022\022\032\n\026SEVERITY_NUMBER_ERROR3\020" +
      "\023\022\032\n\026SEVERITY_NUMBER_ERROR4\020\024\022\031\n\025SEVERIT" +
      "Y_NUMBER_FATAL\020\025\022\032\n\026SEVERITY_NUMBER_FATA" +
      "L2\020\026\022\032\n\026SEVERITY_NUMBER_FATAL3\020\027\022\032\n\026SEVE" +
      "RITY_NUMBER_FATAL4\020\030*X\n\016LogRecordFlags\022\037" +
      "\n\033LOG_RECORD_FLAG_UNSPECIFIED\020\000\022%\n LOG_R" +
      "ECORD_FLAG_TRACE_FLAGS_MASK\020\377\001BU\n\036io.ope" +
      "ntelemetry.proto.logs.v1B\tLogsProtoP\001Z&g" +
      "o.opentelemetry.io/proto/otlp/logs/v1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor,
        new java.lang.String[] { "ResourceLogs", });
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor,
        new java.lang.String[] { "Resource", "InstrumentationLibraryLogs", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "LogRecords", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor,
        new java.lang.String[] { "TimeUnixNano", "ObservedTimeUnixNano", "SeverityNumber", "SeverityText", "Name", "Body", "Attributes", "DroppedAttributesCount", "Flags", "TraceId", "SpanId", });
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
