// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace/v1/trace_config.proto

package io.opentelemetry.proto.trace.v1;

public interface ConstantSamplerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.trace.v1.ConstantSampler)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision decision = 1;</code>
   * @return The enum numeric value on the wire for decision.
   */
  int getDecisionValue();
  /**
   * <code>.opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision decision = 1;</code>
   * @return The decision.
   */
  io.opentelemetry.proto.trace.v1.ConstantSampler.ConstantDecision getDecision();
}
