// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/metrics/v1/metrics_service.proto

package io.opentelemetry.proto.collector.metrics.v1;

public interface ExportMetricsServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse)
    com.google.protobuf.MessageOrBuilder {
}
