// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v1/metrics.proto

package io.opentelemetry.proto.metrics.v1;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030metrics/v1/metrics.proto\022\036opentelemetr" +
      "y.proto.metrics.v1\032\026common/v1/common.pro" +
      "to\032\032resource/v1/resource.proto\"X\n\013Metric" +
      "sData\022I\n\020resource_metrics\030\001 \003(\0132/.opente" +
      "lemetry.proto.metrics.v1.ResourceMetrics" +
      "\"\312\001\n\017ResourceMetrics\022;\n\010resource\030\001 \001(\0132)" +
      ".opentelemetry.proto.resource.v1.Resourc" +
      "e\022f\n\037instrumentation_library_metrics\030\002 \003" +
      "(\0132=.opentelemetry.proto.metrics.v1.Inst" +
      "rumentationLibraryMetrics\022\022\n\nschema_url\030" +
      "\003 \001(\t\"\304\001\n\035InstrumentationLibraryMetrics\022" +
      "V\n\027instrumentation_library\030\001 \001(\01325.opent" +
      "elemetry.proto.common.v1.Instrumentation" +
      "Library\0227\n\007metrics\030\002 \003(\0132&.opentelemetry" +
      ".proto.metrics.v1.Metric\022\022\n\nschema_url\030\003" +
      " \001(\t\"\222\003\n\006Metric\022\014\n\004name\030\001 \001(\t\022\023\n\013descrip" +
      "tion\030\002 \001(\t\022\014\n\004unit\030\003 \001(\t\0226\n\005gauge\030\005 \001(\0132" +
      "%.opentelemetry.proto.metrics.v1.GaugeH\000" +
      "\0222\n\003sum\030\007 \001(\0132#.opentelemetry.proto.metr" +
      "ics.v1.SumH\000\022>\n\thistogram\030\t \001(\0132).opente" +
      "lemetry.proto.metrics.v1.HistogramH\000\022U\n\025" +
      "exponential_histogram\030\n \001(\01324.openteleme" +
      "try.proto.metrics.v1.ExponentialHistogra" +
      "mH\000\022:\n\007summary\030\013 \001(\0132\'.opentelemetry.pro" +
      "to.metrics.v1.SummaryH\000B\006\n\004dataJ\004\010\004\020\005J\004\010" +
      "\006\020\007J\004\010\010\020\t\"M\n\005Gauge\022D\n\013data_points\030\001 \003(\0132" +
      "/.opentelemetry.proto.metrics.v1.NumberD" +
      "ataPoint\"\272\001\n\003Sum\022D\n\013data_points\030\001 \003(\0132/." +
      "opentelemetry.proto.metrics.v1.NumberDat" +
      "aPoint\022W\n\027aggregation_temporality\030\002 \001(\0162" +
      "6.opentelemetry.proto.metrics.v1.Aggrega" +
      "tionTemporality\022\024\n\014is_monotonic\030\003 \001(\010\"\255\001" +
      "\n\tHistogram\022G\n\013data_points\030\001 \003(\01322.opent" +
      "elemetry.proto.metrics.v1.HistogramDataP" +
      "oint\022W\n\027aggregation_temporality\030\002 \001(\01626." +
      "opentelemetry.proto.metrics.v1.Aggregati" +
      "onTemporality\"\303\001\n\024ExponentialHistogram\022R" +
      "\n\013data_points\030\001 \003(\0132=.opentelemetry.prot" +
      "o.metrics.v1.ExponentialHistogramDataPoi" +
      "nt\022W\n\027aggregation_temporality\030\002 \001(\01626.op" +
      "entelemetry.proto.metrics.v1.Aggregation" +
      "Temporality\"P\n\007Summary\022E\n\013data_points\030\001 " +
      "\003(\01320.opentelemetry.proto.metrics.v1.Sum" +
      "maryDataPoint\"\206\002\n\017NumberDataPoint\022;\n\natt" +
      "ributes\030\007 \003(\0132\'.opentelemetry.proto.comm" +
      "on.v1.KeyValue\022\034\n\024start_time_unix_nano\030\002" +
      " \001(\006\022\026\n\016time_unix_nano\030\003 \001(\006\022\023\n\tas_doubl" +
      "e\030\004 \001(\001H\000\022\020\n\006as_int\030\006 \001(\020H\000\022;\n\texemplars" +
      "\030\005 \003(\0132(.opentelemetry.proto.metrics.v1." +
      "Exemplar\022\r\n\005flags\030\010 \001(\rB\007\n\005valueJ\004\010\001\020\002\"\245" +
      "\002\n\022HistogramDataPoint\022;\n\nattributes\030\t \003(" +
      "\0132\'.opentelemetry.proto.common.v1.KeyVal" +
      "ue\022\034\n\024start_time_unix_nano\030\002 \001(\006\022\026\n\016time" +
      "_unix_nano\030\003 \001(\006\022\r\n\005count\030\004 \001(\006\022\013\n\003sum\030\005" +
      " \001(\001\022\025\n\rbucket_counts\030\006 \003(\006\022\027\n\017explicit_" +
      "bounds\030\007 \003(\001\022;\n\texemplars\030\010 \003(\0132(.opente" +
      "lemetry.proto.metrics.v1.Exemplar\022\r\n\005fla" +
      "gs\030\n \001(\rJ\004\010\001\020\002\"\201\004\n\035ExponentialHistogramD" +
      "ataPoint\022;\n\nattributes\030\001 \003(\0132\'.opentelem" +
      "etry.proto.common.v1.KeyValue\022\034\n\024start_t" +
      "ime_unix_nano\030\002 \001(\006\022\026\n\016time_unix_nano\030\003 " +
      "\001(\006\022\r\n\005count\030\004 \001(\006\022\013\n\003sum\030\005 \001(\001\022\r\n\005scale" +
      "\030\006 \001(\021\022\022\n\nzero_count\030\007 \001(\006\022W\n\010positive\030\010" +
      " \001(\0132E.opentelemetry.proto.metrics.v1.Ex" +
      "ponentialHistogramDataPoint.Buckets\022W\n\010n" +
      "egative\030\t \001(\0132E.opentelemetry.proto.metr" +
      "ics.v1.ExponentialHistogramDataPoint.Buc" +
      "kets\022\r\n\005flags\030\n \001(\r\022;\n\texemplars\030\013 \003(\0132(" +
      ".opentelemetry.proto.metrics.v1.Exemplar" +
      "\0320\n\007Buckets\022\016\n\006offset\030\001 \001(\021\022\025\n\rbucket_co" +
      "unts\030\002 \003(\004\"\305\002\n\020SummaryDataPoint\022;\n\nattri" +
      "butes\030\007 \003(\0132\'.opentelemetry.proto.common" +
      ".v1.KeyValue\022\034\n\024start_time_unix_nano\030\002 \001" +
      "(\006\022\026\n\016time_unix_nano\030\003 \001(\006\022\r\n\005count\030\004 \001(" +
      "\006\022\013\n\003sum\030\005 \001(\001\022Y\n\017quantile_values\030\006 \003(\0132" +
      "@.opentelemetry.proto.metrics.v1.Summary" +
      "DataPoint.ValueAtQuantile\022\r\n\005flags\030\010 \001(\r" +
      "\0322\n\017ValueAtQuantile\022\020\n\010quantile\030\001 \001(\001\022\r\n" +
      "\005value\030\002 \001(\001J\004\010\001\020\002\"\301\001\n\010Exemplar\022D\n\023filte" +
      "red_attributes\030\007 \003(\0132\'.opentelemetry.pro" +
      "to.common.v1.KeyValue\022\026\n\016time_unix_nano\030" +
      "\002 \001(\006\022\023\n\tas_double\030\003 \001(\001H\000\022\020\n\006as_int\030\006 \001" +
      "(\020H\000\022\017\n\007span_id\030\004 \001(\014\022\020\n\010trace_id\030\005 \001(\014B" +
      "\007\n\005valueJ\004\010\001\020\002*\214\001\n\026AggregationTemporalit" +
      "y\022\'\n#AGGREGATION_TEMPORALITY_UNSPECIFIED" +
      "\020\000\022!\n\035AGGREGATION_TEMPORALITY_DELTA\020\001\022&\n" +
      "\"AGGREGATION_TEMPORALITY_CUMULATIVE\020\002*;\n" +
      "\016DataPointFlags\022\r\n\tFLAG_NONE\020\000\022\032\n\026FLAG_N" +
      "O_RECORDED_VALUE\020\001B^\n!io.opentelemetry.p" +
      "roto.metrics.v1B\014MetricsProtoP\001Z)go.open" +
      "telemetry.io/proto/otlp/metrics/v1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor,
        new java.lang.String[] { "ResourceMetrics", });
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor,
        new java.lang.String[] { "Resource", "InstrumentationLibraryMetrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "Metrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor,
        new java.lang.String[] { "Name", "Description", "Unit", "Gauge", "Sum", "Histogram", "ExponentialHistogram", "Summary", "Data", });
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", "IsMonotonic", });
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "AsDouble", "AsInt", "Exemplars", "Flags", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "BucketCounts", "ExplicitBounds", "Exemplars", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "Scale", "ZeroCount", "Positive", "Negative", "Flags", "Exemplars", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor,
        new java.lang.String[] { "Offset", "BucketCounts", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "QuantileValues", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor,
        new java.lang.String[] { "Quantile", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor,
        new java.lang.String[] { "FilteredAttributes", "TimeUnixNano", "AsDouble", "AsInt", "SpanId", "TraceId", "Value", });
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
