// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/logs/v1/logs_service.proto

package io.opentelemetry.proto.collector.logs.v1;

public interface ExportLogsServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)
    com.google.protobuf.MessageOrBuilder {
}
