// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v1/common.proto

package io.opentelemetry.proto.common.v1;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_common_v1_AnyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_common_v1_AnyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_common_v1_ArrayValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_common_v1_ArrayValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_common_v1_KeyValueList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_common_v1_KeyValueList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_common_v1_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_common_v1_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_common_v1_InstrumentationLibrary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_common_v1_InstrumentationLibrary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026common/v1/common.proto\022\035opentelemetry." +
      "proto.common.v1\"\214\002\n\010AnyValue\022\026\n\014string_v" +
      "alue\030\001 \001(\tH\000\022\024\n\nbool_value\030\002 \001(\010H\000\022\023\n\tin" +
      "t_value\030\003 \001(\003H\000\022\026\n\014double_value\030\004 \001(\001H\000\022" +
      "@\n\013array_value\030\005 \001(\0132).opentelemetry.pro" +
      "to.common.v1.ArrayValueH\000\022C\n\014kvlist_valu" +
      "e\030\006 \001(\0132+.opentelemetry.proto.common.v1." +
      "KeyValueListH\000\022\025\n\013bytes_value\030\007 \001(\014H\000B\007\n" +
      "\005value\"E\n\nArrayValue\0227\n\006values\030\001 \003(\0132\'.o" +
      "pentelemetry.proto.common.v1.AnyValue\"G\n" +
      "\014KeyValueList\0227\n\006values\030\001 \003(\0132\'.opentele" +
      "metry.proto.common.v1.KeyValue\"O\n\010KeyVal" +
      "ue\022\013\n\003key\030\001 \001(\t\0226\n\005value\030\002 \001(\0132\'.opentel" +
      "emetry.proto.common.v1.AnyValue\"7\n\026Instr" +
      "umentationLibrary\022\014\n\004name\030\001 \001(\t\022\017\n\007versi" +
      "on\030\002 \001(\tB[\n io.opentelemetry.proto.commo" +
      "n.v1B\013CommonProtoP\001Z(go.opentelemetry.io" +
      "/proto/otlp/common/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_opentelemetry_proto_common_v1_AnyValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_common_v1_AnyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_common_v1_AnyValue_descriptor,
        new java.lang.String[] { "StringValue", "BoolValue", "IntValue", "DoubleValue", "ArrayValue", "KvlistValue", "BytesValue", "Value", });
    internal_static_opentelemetry_proto_common_v1_ArrayValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_common_v1_ArrayValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_common_v1_ArrayValue_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_opentelemetry_proto_common_v1_KeyValueList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_common_v1_KeyValueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_common_v1_KeyValueList_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_opentelemetry_proto_common_v1_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_common_v1_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_common_v1_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_opentelemetry_proto_common_v1_InstrumentationLibrary_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_common_v1_InstrumentationLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_common_v1_InstrumentationLibrary_descriptor,
        new java.lang.String[] { "Name", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
