// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v1/common.proto

package io.opentelemetry.proto.common.v1;

public interface InstrumentationLibraryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.common.v1.InstrumentationLibrary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An empty instrumentation library name means the name is unknown. 
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * An empty instrumentation library name means the name is unknown. 
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
